name: Deploy App Service Python

on:
  #push:
  workflow_dispatch:

env:
  ACTIONS_RUNNER_DEBUG: true
  AZURE_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
  AZURE_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  AZURE_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  APP_SERVICE_NAME: "${{ vars.APP_SERVICE_NAME}}"
  APP_RESOURCE_GROUP: "${{ vars.APP_RESOURCE_GROUP}}"
  ZIP_FILE_NAME: "app.zip"

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: [self-hosted, python]
    steps:
      - uses: actions/checkout@v4

      - name: Get packages
        run: |
          cd quickstart_python
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Zip the code
        run: |
          cd quickstart_python
          zip -r ${{ env.ZIP_FILE_NAME }} .

      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}


      - name: Deploy Pub Function
        run: |
          az webapp deploy \
              --name  ${{ env.APP_SERVICE_NAME }} \
              --resource-group ${{ env.APP_RESOURCE_GROUP }} \
              --src-path quickstart_python/${{ env.ZIP_FILE_NAME }}
